---
name: yamllint
# yamllint disable rule:truthy
on: [push, pull_request]
# yamllint enable rule:truthy
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: bewuethr/yamllint-action@v1
        with:
          config-file: .yamllint
